AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
Globals:
  Function:
    CodeUri: ./src
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 15
    Tracing: Active
Resources:
  EventConsumerA:
    Type: AWS::Serverless::Function
    Properties:
      Handler: EventConsumer.handler
      Events:
        EventRule:
          Type: EventBridgeRule
          Properties:
            EventBusName: custom
            Pattern:
              source: 
                - service-b
  EventConsumerB:
    Type: AWS::Serverless::Function
    Properties:
      Handler: EventConsumer.handler
      Events:
        EventRule:
          Type: EventBridgeRule
          Properties:
            EventBusName: custom
            Pattern:
              source: 
                - service-b
