version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "xray-test-service-b"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o6vnxeqicluu"
s3_prefix = "xray-test-service-b"
region = "eu-west-1"
profile = "private"
capabilities = "CAPABILITY_IAM"
image_repositories = []
