AWSTemplateFormatVersion: 2010-09-09
Transform:
  - Name: env-event-utils-DynamoTrigger
    Parameters:
      TableName: DynamoTable
      EventBusName: custom
  - 'AWS::Serverless-2016-10-31'
Globals:
  Function:
    CodeUri: ./src
    Runtime: nodejs14.x
    Timeout: 15
    Tracing: Active
Resources:
  PutItem:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: PutItem.handler
      Events:
        PutItem:
          Type: Api
          Properties:
            Method: put
            Path: /item
            RestApiId: !Ref Api
      CodeUri: src/
      Runtime: nodejs14.x
      Timeout: 3
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref DynamoTable
  DynamoTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  Api:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Prod
      TracingEnabled: true
  # DynamoDbTrigger:
  #   Type: 'AWS::Serverless::Function'
  #   Properties:
  #     Handler: DynamoDbTrigger.handler
  #     Runtime: nodejs14.x
  #     CodeUri: src/
  #     MemorySize: 128
  #     Timeout: 3
  #     Events:
  #       DynamoTable:
  #         Type: DynamoDB
  #         Properties:
  #           Stream: !GetAtt DynamoTable.StreamArn
  #           StartingPosition: TRIM_HORIZON
  #           BatchSize: 100
  #     Policies:
  #       - Version: 2012-10-17
  #         Statement:
  #           - Sid: Statement1
  #             Effect: Allow
  #             Action:
  #               - 'events:PutEvents'
  #             Resource:
  #               - '*'
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: custom

Outputs:
  ApiGatewayUrl:
    Value: !Sub 'https://${Api}.execute-api.eu-west-1.amazonaws.com/Prod'
